sources:
  - name: vision-v1-subgraph
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/dowlandaiello/vision-v1-subgraph

plugins:
  - pollingLive:
      defaultInterval: 1000

documents:
  - ./lib/queries/map.graphql
  - ./lib/queries/search.graphql
  - ./lib/queries/user.graphql
