sources:
  - name: vision-v1-subgraph
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/dowlandaiello/vision-v1-subgraph
  - name: uniswap-v2
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/dowlandaiello/uniswap-v3-subgraph-mumbai

plugins:
  - pollingLive:
      defaultInterval: 5000

documents:
  - ./lib/queries/map.graphql
  - ./lib/queries/search.graphql
  - ./lib/queries/user.graphql
  - ./lib/queries/dao.graphql
  - ./lib/queries/prop.graphql
